version: "3.8"

services:
  app:
    build: .
    container_name: trend-finder
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    networks:
      - trend-network

networks:
  trend-network:
    driver: bridge
