name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          # Create a tar of the build files
          tar -czf build.tar.gz dist package*.json .env.example

          # Copy files to server using sshpass
          sshpass -e scp build.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/app/

          # Execute remote commands using sshpass
          sshpass -e ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            cd ~/app
            tar -xzf build.tar.gz
            npm ci --production
            cp .env.example .env
            pm2 delete trend-finder || true
            pm2 start dist/index.js --name trend-finder
            rm build.tar.gz
          '
