name: Deploy to Production # 部署到生产环境

on:
  push:
    tags:
      - "v*" # 当创建以v开头的tag时触发
  workflow_dispatch: # 允许手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest # 在最新版本的 Ubuntu 运行器上运行

    steps:
      - uses: actions/checkout@v4 # 检出代码

      - name: Setup SSH # 设置 SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Check and Install Deno on Server # 检查并安装 Deno
        run: |
          ssh -i ~/.ssh/id_rsa "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" '
            if ! command -v deno &> /dev/null; then
              echo "Installing Deno..."
              curl -fsSL https://deno.land/x/install/install.sh | sh
              echo "export DENO_INSTALL=\"\$HOME/.deno\"" >> ~/.bashrc
              echo "export PATH=\"\$DENO_INSTALL/bin:\$PATH\"" >> ~/.bashrc
              source ~/.bashrc
            else
              echo "Deno is already installed"
              deno --version
            fi
          '

      - name: Create .env file # 创建环境配置文件
        run: |
          cat > .env << EOL
          # 数据库配置
          ENABLE_DB=true
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          EOL
          
      - name: Get Deno Path # 获取 Deno 路径
        run: |
          DENO_PATH=$(ssh -i ~/.ssh/id_rsa "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" "which deno || echo \$HOME/.deno/bin/deno")
          echo "DENO_PATH=$DENO_PATH" >> $GITHUB_ENV
          echo "Deno path: $DENO_PATH"

      - name: Create PM2 Config # 创建 PM2 配置文件
        run: |
          cat > ecosystem.config.js << EOL
          module.exports = {
            apps: [{
              name: 'trend-finder',
              script: 'deno task start',
              interpreter: '${{ env.DENO_PATH }}',
              env: {
                NODE_ENV: 'production'
              }
            }]
          }
          EOL
          scp -i ~/.ssh/id_rsa ecosystem.config.js "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/app/"

      - name: Deploy to Server # 部署到服务器
        run: |
          # 确保目录存在
          ssh -i ~/.ssh/id_rsa "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" "mkdir -p ~/app"

          # 复制项目文件
          scp -r -i ~/.ssh/id_rsa ./* "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/app/"
          scp -i ~/.ssh/id_rsa .env "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/app/"

          # 检查并安装 pm2
          ssh -i ~/.ssh/id_rsa "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" "
            if ! command -v pm2 &> /dev/null; then
              echo '安装 pm2...'
              npm install -g pm2
              export PATH=\"\$HOME/.npm-global/bin:\$PATH\"
            fi
          "

          # 使用 PM2 配置文件启动
          ssh -i ~/.ssh/id_rsa "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" "
            cd ~/app && \
            export DENO_INSTALL=\"\$HOME/.deno\" && \
            export PATH=\"\$HOME/.deno/bin:\$PATH\" && \
            if pm2 list | grep -q 'trend-finder'; then
              pm2 stop trend-finder
              pm2 delete trend-finder
            fi && \
            pm2 start ecosystem.config.js
          "
          
      - name: Verify Deployment # 验证部署
        run: |
          echo "部署完成，正在验证..."
          ssh -i ~/.ssh/id_rsa "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" "
            if pm2 list | grep -q 'trend-finder.*online'; then
              echo '✅ 应用已成功部署并运行'
              exit 0
            else
              echo '❌ 应用部署失败或未正常运行'
              pm2 logs trend-finder --lines 20
              exit 1
            fi
          "
