name: Deploy to Production # 部署到生产环境

on:
  push:
    tags:
      - "v*" # 当创建以v开头的tag时触发
  workflow_dispatch: # 允许手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest # 在最新版本的 Ubuntu 运行器上运行

    steps:
      - uses: actions/checkout@v4 # 检出代码

      - name: Create .env file # 创建环境配置文件
        run: |
          cat > .env << EOL
          # 数据库配置
          ENABLE_DB=true
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          EOL

      - name: Setup SSH # 设置 SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to Server # 部署到服务器
        run: |
          ssh -i ~/.ssh/id_rsa "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" "
            cd ~/app || mkdir -p ~/app && cd ~/app
            rm -rf ./* ./.* 2>/dev/null || true
            git clone https://github.com/OpenAISpace/ai-trend-publish
            cd ai-trend-publish
          "
          scp -i ~/.ssh/id_rsa .env "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/app/ai-trend-publish/"
          ssh -i ~/.ssh/id_rsa "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" "
            cd ~/app/ai-trend-publish
            pm2 delete trend-finder 2>/dev/null || true
            pm2 start --name trend-finder 'deno run --allow-all start'
            echo '部署完成'
          "
